spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmyDB
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    username: soumosirmaryland@gmail.com
    password: eublqkrgohtwpnns
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#server:
#  port: 443
#  ssl:
#    key-store-password: ssldutta
#    key-store-type: PKCS12
#    key-store: classpath:keystore/sduttakeystore.p12
#    key-alias: sduttabook
#    enabled: 'true'
#    trust-store: classpath:keystore/sduttakeystore.p12                6
#    trust-store-password: ssldutta

server:
  port: 8443
  ssl:
    key-store: classpath:sduttakeystore.p12
    key-store-password: ssldutta
    key-store-type: PKCS12
    key-alias: sduttabook
    key-password: ssldutta
    enabled: true

#trust:
#  store:
#    nodeValue: classpath:keystore/sduttakeystore.p12
#    password: ssldutta

logging:
  file:
    path: /
    name: log.txt
  level:
    com.umd.hrm: debug

#server.ssl = 443
## The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
## The path to the keystore containing the certificate
#server.ssl.key-store=classpath:keystore/sduttakeystore.p12
## The password used to generate the certificate
#server.ssl.key-store-password=ssldutta
## The alias mapped to the certificate
#server.ssl.key-alias=sduttabook
#
#server.ssl.enabled=true
#
##trust store location
#trust.store=classpath:keystore/sduttakeystore.p12
##trust store password
#trust.store.password=ssldutta

